### ISSUE TITLE
Please explain 'The nvim-cmp almost supports LSP's capabilities so You should advertise it to LSP servers..'

### ISSUE THREAD

**Issue by David-Else** [hrsh7th/cmp-nvim-lsp#3]
```lua
-- The nvim-cmp almost supports LSP's capabilities so You should advertise it to LSP servers..
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- The following example advertise capabilities to `clangd`.
require'lspconfig'.clangd.setup {
  capabilities = capabilities,
}
```
I don't think the user should be expected to understand exactly how the LSP server in Neovim works to use it. Please could you add a paragraph to explain what is going on here and more detail on how and where to add this code?

For example, what if I don't have a snippet plugin installed and this tells the server that `nvim-cmp` accepts snippets? Is that a problem, or is all that automated in the latest `feat: Make setup easier` patch?

- Why is it needed? `nvim-cmp` seems to be working in all LSP servers I have tried **without** this setting, it is very mysterious. Will I be missing certain features not using it?
- How about if my `nvim-cmp` settings are in a different file to my general LSP settings, where should the above code go?

Sorry, please assume that users are just coming from VS Code and want things to work with as few settings as possible :) Thanks!

**Comment by hrsh7th** [comment]
I can't explain everything... LSP and neovim and neovim-lspconfig and snippets and nvim-cmp and vim's mapping mechanism...

I just can only try to provide the best completion experience to the neovim community.

1. What is LSP?
2. What are capabilities?
3. Explain each capabilities that supported by nvim-cmp
4. Why the server works well if I hadn't configure the capabilities?
→ Because some server ignores capabilities.

**Comment by hrsh7th** [comment]
I'm really sorry, but it's the most difficult request for me.

**Comment by ViViDboarder** [comment]
I have a question about this enhanced capabilities too.

It seems like this feature tells my language server, `gopls`, that my completion accepts snippets. This seems cool because I know `nvim-cmp` does support snippets and I can see them populated in the complete list. However, it doesn't appear that `nvim-cmp` expands snippets provided in this way. It seems that `nvim-cmp` asks that I provide an `expand` function, but it doesn't look like one is actually provided by `cmp-nvim-lsp`.

Am I missing something, or should this capability not be updated to `true`?

**Comment by gegoune** [comment]
You need snippets engine for snippets to work, luasnip is a popular choice these days. Once you get that installed you need to tell cmp how to expand snippets, by `expand` function.
